### ISSUE TITLE
Remove fake bioportal MTH IDs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/malco#16]

**Comment by caufieldjh** [comment]
Probably a fix for `ontogpt`, unless the plan here is to just remove them before scoring.

In some cases these really should be MONDO terms anyway, like http://purl.bioontology.org/ontology/OMIM/MTHU037698
Though in other cases they aren't diseases or phenotypes at all, like http://purl.bioontology.org/ontology/OMIM/MTHU001678 ("X-linked")

**Comment by justaddcoffee** [comment]
For example IDs like `OMIM:MTHU036349`


```
extracted_object:
  id: fa86d027-d8cc-4cff-8ae7-4a255c69bccc
  label: STX_EG0519P.json_en-prompt.txt
  terms:
    - OMIM:105830
    - OMIM:312750
    - OMIM:300624
    - OMIM:MTHU004242
    - OMIM:MTHU036349
    - OMIM:277900
    - OMIM:MTHU000136
    - MONDO:0018772
[snip]
 ```
